version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" js /root/mine.js'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/ks1:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dag/:/root/.ethash/:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  bootstrap2:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap2
    hostname: bootstrap2
    links:
      - netstats
      - bootstrap
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" js /root/mine.js'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/ks2:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dag/:/root/.ethash/:rw
    ports:
      - "30304:30303"
      - "30304:30303/udp"
      - "8546:8545"
  eth3:
    build: monitored-geth-client
    restart: on-failure
    hostname: eth3
    container_name: eth3
    links:
      - bootstrap
      - bootstrap2
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/ks3:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dag/:/root/.ethash/:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" js /root/mine.js'
  eth4:
    build: monitored-geth-client
    restart: on-failure
    hostname: eth4
    container_name: eth4
    links:
      - bootstrap
      - bootstrap2
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/ks4:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dag/:/root/.ethash/:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" js /root/mine.js'
  eth5:
    build: monitored-geth-client
    restart: on-failure
    hostname: eth5
    container_name: eth5
    links:
      - bootstrap
      - bootstrap2
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/ks5:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dag/:/root/.ethash/:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" js /root/mine.js'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
